export const LISTAR_TODOS_REQUEST = 'LISTAR_TODOS_REQUEST'
export const LISTAR_TODOS_SUCCESS = 'LISTAR_TODOS_SUCCESS'
export const LISTAR_TODOS_ERROR = 'LISTAR_TODOS_ERROR'

export const DELETAR_REQUEST  = 'DELETAR_REQUEST'
export const DELETAR_SUCCESS = 'DELETAR_SUCCESS'

export const LISTAR_POR_ID_REQUEST = 'LISTAR_POR_ID_REQUEST'
export const LISTAR_POR_ID_SUCCESS = 'LISTAR_POR_ID_SUCCESS'
