version: "3.9"

services:
    app:
        database_clinica:
            image: postgres
            container_name: database_clinica
            restart: always
            ports: 
                - 5434:5432
            environment: 
                - POSTGRES_USER=docker
                - POSTGRES_PASSWORD=123456
                - POSTGRES_DB=servicoshospitalares
            volumes: 
                - pgdata:/data/postgres
        build: .
        container_name: backend
        ports:
            - 3333:3333
        volumes: 
            - .:/usr/app

volumes: 
    pgdata:
        driver: local