export const CADASTRAR_MEDICO_REQUEST = 'CADASTRAR_MEDICO_REQUEST'
export const CADASTRAR_MEDICO_SUCCESS = 'CADASTRAR_MEDICO_SUCCESS'

export const LISTAR_TODOS_MEDICOS_REQUEST = 'LISTAR_TODOS_MEDICOS_REQUEST'
export const LISTAR_TODOS_MEDICOS_SUCCESS = 'LISTAR_TODOS_MEDICOS_SUCCESS'