export const CADASTRO_USUARIO_REQUEST = 'CADASTRO_USUARIO_REQUEST'
export const CADASTRO_USUARIO_SUCCESS = 'CADASTRO_USUARIO_SUCCESS'

export const AUTENTICAR_USUARIO_REQUEST = 'AUTENTICAR_USUARIO_REQUEST'
export const AUTENTICAR_USUARIO_SUCCESS = 'AUTENTICAR_USUARIO_SUCCESS'

export const LOGOUT_USUARIO_REQUEST = 'LOGOUT_USUARIO_REQUEST'
export const LOGOUT_USUARIO_SUCCESS = 'LOGOUT_USUARIO_SUCCESS'






