export const CADASTRO_CLINICA_REQUEST = 'CADASTRO_CLINICA_REQUEST'
export const CADASTRO_CLINICA_SUCCESS = 'CADASTRO_CLINICA_SUCCESS'

export const LISTAR_TODAS_CLINICAS_REQUEST = 'LISTAR_TODAS_CLINICAS_REQUEST'
export const LISTAR_TODAS_CLINICAS_SUCCESS = 'LISTAR_TODAS_CLINICAS_SUCCESS'

export const DELETAR_CLINICAS_REQUEST  = 'DELETAR_CLINICAS_REQUEST'
export const DELETAR_CLINICAS_SUCCESS = 'DELETAR_CLINICAS_SUCCESS'

export const LISTAR_CLINICAS_POR_ID_REQUEST = 'LISTAR_CLINICAS_POR_ID_REQUEST'
export const LISTAR_CLINICAS_POR_ID_SUCCESS = 'LISTAR_CLINICAS_POR_ID_SUCCESS'

export const ATUALIZA_CLINICA_REQUEST = 'ATUALIZA_CLINICA_REQUEST'
export const ATUALIZA_CLINICA_SUCCESS = 'ATUALIZA_CLINICA_SUCCESS'

export const LIMPAR_DADOS_DA_CLINICA = 'LIMPAR_DADOS_DA_CLINICA'

export const LISTA_CLINICA_POR_ID_AGENDAMENTO = 'LISTA_CLINICA_POR_ID_AGENDAMENTO'


